QT_ARCH = x86_64
QT_BUILDABI = x86_64-little_endian-lp64
QT.global.enabled_features = c++11 c++14 c++1z concurrent pkg-config static
QT.global.disabled_features = cross_compile framework shared rpath appstore-compliant debug_and_release simulator_and_device build_all force_asserts separate_debug_info
CONFIG += release static
QT_CONFIG += release c++11 c++14 c++1z concurrent dbus reduce_exports reduce_relocations static stl
QT_VERSION = 5.10.1
QT_MAJOR_VERSION = 5
QT_MINOR_VERSION = 10
QT_PATCH_VERSION = 1
QT_GCC_MAJOR_VERSION = 4
QT_GCC_MINOR_VERSION = 2
QT_GCC_PATCH_VERSION = 1
QT_CLANG_MAJOR_VERSION = 5
QT_CLANG_MINOR_VERSION = 0
QT_CLANG_PATCH_VERSION = 1
QT_EDITION = OpenSource
